# Generated by Django 4.2.30 on 2026-08-05 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_portal', '0001_create_edl_admin_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdlAdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_user', 'Create user'), ('deactivate_user', 'Deactivate user'), ('reactivate_user', 'Reactivate user'), ('enroll', 'Enroll'), ('unenroll', 'Unenroll'), ('role_grant', 'Grant course role'), ('role_revoke', 'Revoke course role')], max_length=64)),
                ('target_identifier', models.CharField(blank=True, help_text='Email/username when the target is not (yet) a user row (e.g. a pending enrollment).', max_length=254)),
                ('course_id', models.CharField(blank=True, max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Admin who performed the action (null if the actor was later removed).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edl_admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text='Affected user, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edl_admin_targeted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EDL admin audit entry',
                'verbose_name_plural': 'EDL admin audit log',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['action', 'created'], name='admin_porta_action_8ba13a_idx'), models.Index(fields=['target_user', 'created'], name='admin_porta_target__b56d08_idx')],
            },
        ),
    ]
